### PR TITLE
[OC-2058] Fixed favorite products

### PR DESCRIPTION
**Pull request by Labedlam**

### CODE REVIEW

**Comment by robertsoniv** [comment]
@Labedlam was this really all we were missing?

**Comment by Labedlam** [comment]
That's how I got it to work in the cups app, which was having the same issue.

**Comment by crhistianr** [comment]
Is this good to merge in or are we waiting on something?

**Comment by robertsoniv** [comment]
I believe @labedlam said this was fixed after his second commit.

**Pull request merged**
